name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
    - uses: actions/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build the Docker image
    - uses: actions/checkout@v3
      run: |
        docker build -t chatgpt-discord-bot .
        docker tag chatgpt-discord-bot:latest aehryn/chatgpt-discord-bot:latest
        docker push aehryn/chatgpt-discord-bot:latest
