name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker build -t ChatGPT-Discord-Bot .
        docker tag ChatGPT-Discord-Bot:latest aehryn/ChatGPT-Discord-Bot:latest
        docker push aehryn/ChatGPT-Discord-Bot:latest
